name: Python Package using Pip

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8.15
      uses: actions/setup-python@v3
      with:
        python-version: '3.8.15'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install numpy==1.24.1 pandas==1.5.3 scikit-learn==1.0.2 pytest==7.2.1 requests==2.28.2 fastapi==0.63.0 uvicorn==0.20.0 gunicorn==20.1.0
        
    - name: Test with pytest
      run: |
        pytest
        
    - name: Lint with flake8
      run: |
        pip install flake8



